name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch tags for hatch-vcs
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install hatch
      - name: Run tests
        run: |
          python -m pip install -e .
          pytest -q

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch tags for hatch-vcs
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pin version in pyproject from tag
        run: |
          V="${GITHUB_REF_NAME#v}"
          # Patch pyproject.toml in-place (avoid heredoc to keep YAML valid)
          python - "$V" -c "import re,sys; p='pyproject.toml'; s=open(p,'r',encoding='utf-8').read(); s=re.sub(r'(?m)^dynamic\\s*=\\s*\\[\\s*\"version\"\\s*\\]\\s*$', 'version = \"'+sys.argv[1]+'\"', s); s=re.sub(r'(?ms)^\\[tool\\.hatch\\.version\\].*?(?=^\\[|\\Z)', '', s); open(p,'w',encoding='utf-8').write(s)"
      - name: Build
        run: |
          python -m pip install -U pip hatch
          rm -rf dist
          hatch build
          ls -la dist
      - name: Validate artifacts (no dev wheels)
        run: |
          if ls dist/*dev* 2>/dev/null; then
            echo "Dev/local version artifacts found in dist/. Aborting publish." >&2
            exit 1
          fi
      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
