name: windows-smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
          python -m pip install -e .
      - name: Smoke test CLI
        shell: pwsh
        run: |
          teds --version
          teds verify demo/sample_tests.yaml --output-level warning
          if ($LASTEXITCODE -ne 1) {
            echo "Expected exit code 1, got $LASTEXITCODE"
            exit 1
          }
